<?php

namespace Database\Seeders;

use App\Models\Announcement;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class AnnouncementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Announcement::create([
            'title' => 'Pengumuman Libur',
            'announcement_category_id' => 1,
            'slug' => Str::slug('Pengumuman Libur'),
            'body' => '<p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consequat commodo risus eu malesuada. Aliquam eu libero tincidunt, egestas massa in, ullamcorper lorem. Maecenas sit amet aliquet risus. Praesent varius augue a tempor lobortis. Cras auctor ac arcu a porta. Sed sodales laoreet dui, at feugiat magna porttitor non. Sed egestas, justo a consequat egestas, quam sapien malesuada justo, non tempus sapien ante congue odio. In arcu magna, suscipit nec pellentesque ac, maximus sit amet velit. Phasellus sit amet urna a nunc efficitur hendrerit et non velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus placerat finibus purus a mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent vitae posuere sapien.</p><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">Donec auctor urna nibh, vitae facilisis nunc porttitor quis. Nunc non metus turpis. Nullam ornare feugiat orci, at ornare sem dignissim eu. Maecenas mattis augue eu luctus aliquet. Vivamus felis tellus, eleifend eget scelerisque sed, bibendum sit amet justo. Suspendisse potenti. Integer congue at felis vel tristique. Ut vel bibendum mauris, ac blandit orci. Curabitur sollicitudin nunc eu mi lobortis pulvinar. In sit amet dolor eget elit posuere placerat vel quis tellus. Praesent facilisis pharetra tellus, et pretium urna faucibus in. Phasellus mauris metus, euismod ut arcu nec, gravida auctor augue. Duis a congue lacus, vitae placerat nibh. Praesent semper diam eget bibendum efficitur. Aliquam rutrum turpis eros, hendrerit sollicitudin leo faucibus non.</p><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">In porta cursus ante at iaculis. Sed scelerisque eu tellus nec ultricies. Fusce iaculis finibus nisi et sollicitudin. Nunc vitae tortor sit amet mauris pulvinar pulvinar. Aliquam erat volutpat. Sed maximus, tortor ut eleifend cursus, odio leo blandit ligula, nec eleifend velit nunc vel sem. Donec tincidunt nulla erat, eget rhoncus elit egestas vel. Phasellus porttitor porta rutrum. Sed auctor cursus urna, a pulvinar nibh pellentesque dapibus. Phasellus in ex ligula. Pellentesque vitae lacus et nulla vestibulum venenatis. Donec sed enim nibh.</p>'
        ]);


        Announcement::create([
            'title' => 'Pengumuman Pengambilan Rapor',
            'announcement_category_id' => 1,
            'slug' => Str::slug('Pengumuman Pengambilan Rapor'),
            'body' => '<p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consequat commodo risus eu malesuada. Aliquam eu libero tincidunt, egestas massa in, ullamcorper lorem. Maecenas sit amet aliquet risus. Praesent varius augue a tempor lobortis. Cras auctor ac arcu a porta. Sed sodales laoreet dui, at feugiat magna porttitor non. Sed egestas, justo a consequat egestas, quam sapien malesuada justo, non tempus sapien ante congue odio. In arcu magna, suscipit nec pellentesque ac, maximus sit amet velit. Phasellus sit amet urna a nunc efficitur hendrerit et non velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus placerat finibus purus a mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent vitae posuere sapien.</p><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">Donec auctor urna nibh, vitae facilisis nunc porttitor quis. Nunc non metus turpis. Nullam ornare feugiat orci, at ornare sem dignissim eu. Maecenas mattis augue eu luctus aliquet. Vivamus felis tellus, eleifend eget scelerisque sed, bibendum sit amet justo. Suspendisse potenti. Integer congue at felis vel tristique. Ut vel bibendum mauris, ac blandit orci. Curabitur sollicitudin nunc eu mi lobortis pulvinar. In sit amet dolor eget elit posuere placerat vel quis tellus. Praesent facilisis pharetra tellus, et pretium urna faucibus in. Phasellus mauris metus, euismod ut arcu nec, gravida auctor augue. Duis a congue lacus, vitae placerat nibh. Praesent semper diam eget bibendum efficitur. Aliquam rutrum turpis eros, hendrerit sollicitudin leo faucibus non.</p><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">In porta cursus ante at iaculis. Sed scelerisque eu tellus nec ultricies. Fusce iaculis finibus nisi et sollicitudin. Nunc vitae tortor sit amet mauris pulvinar pulvinar. Aliquam erat volutpat. Sed maximus, tortor ut eleifend cursus, odio leo blandit ligula, nec eleifend velit nunc vel sem. Donec tincidunt nulla erat, eget rhoncus elit egestas vel. Phasellus porttitor porta rutrum. Sed auctor cursus urna, a pulvinar nibh pellentesque dapibus. Phasellus in ex ligula. Pellentesque vitae lacus et nulla vestibulum venenatis. Donec sed enim nibh.</p>'
        ]);


        Announcement::create([
            'title' => 'Pengumuman Beasiswa',
            'announcement_category_id' => 2,
            'slug' => Str::slug('Pengumuman Beasiswa'),
            'body' => '<p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consequat commodo risus eu malesuada. Aliquam eu libero tincidunt, egestas massa in, ullamcorper lorem. Maecenas sit amet aliquet risus. Praesent varius augue a tempor lobortis. Cras auctor ac arcu a porta. Sed sodales laoreet dui, at feugiat magna porttitor non. Sed egestas, justo a consequat egestas, quam sapien malesuada justo, non tempus sapien ante congue odio. In arcu magna, suscipit nec pellentesque ac, maximus sit amet velit. Phasellus sit amet urna a nunc efficitur hendrerit et non velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus placerat finibus purus a mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent vitae posuere sapien.</p><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">Donec auctor urna nibh, vitae facilisis nunc porttitor quis. Nunc non metus turpis. Nullam ornare feugiat orci, at ornare sem dignissim eu. Maecenas mattis augue eu luctus aliquet. Vivamus felis tellus, eleifend eget scelerisque sed, bibendum sit amet justo. Suspendisse potenti. Integer congue at felis vel tristique. Ut vel bibendum mauris, ac blandit orci. Curabitur sollicitudin nunc eu mi lobortis pulvinar. In sit amet dolor eget elit posuere placerat vel quis tellus. Praesent facilisis pharetra tellus, et pretium urna faucibus in. Phasellus mauris metus, euismod ut arcu nec, gravida auctor augue. Duis a congue lacus, vitae placerat nibh. Praesent semper diam eget bibendum efficitur. Aliquam rutrum turpis eros, hendrerit sollicitudin leo faucibus non.</p><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">In porta cursus ante at iaculis. Sed scelerisque eu tellus nec ultricies. Fusce iaculis finibus nisi et sollicitudin. Nunc vitae tortor sit amet mauris pulvinar pulvinar. Aliquam erat volutpat. Sed maximus, tortor ut eleifend cursus, odio leo blandit ligula, nec eleifend velit nunc vel sem. Donec tincidunt nulla erat, eget rhoncus elit egestas vel. Phasellus porttitor porta rutrum. Sed auctor cursus urna, a pulvinar nibh pellentesque dapibus. Phasellus in ex ligula. Pellentesque vitae lacus et nulla vestibulum venenatis. Donec sed enim nibh.</p>'
        ]);
    }
}
